spring.application.name=myBlogPost

spring.datasource.url=jdbc:mysql://myblogdatabase.c3y0ykk4627v.ap-south-1.rds.amazonaws.com:3306/myBlogDb


spring.datasource.username=admin
spring.datasource.password=12345678

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:mysql://localhost:3306/nit
#spring.datasource.username=root
#spring.datasource.password=0000

#S3 configuration
aws.access.key=AKIASBBKL2ZAKYYN4LXJ
aws.secret.key=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
aws.region=ap-south-1
aws.s3.bucket=my-springboot-file-storage



